package PARKINGSYSTEMUNSIKA;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.List;
/**
 *
 * @author salsa
 */
public class PARKIR extends javax.swing.JFrame {
private ParkingDAO parkirData;
    /**
     * Creates new form ADMIN
     */


    public PARKIR() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maksimalkan layar
        try {
        // Inisialisasi parkirData
        parkirData = new ParkingDAO();
    } catch (SQLException e) {
        // Tampilkan error jika terjadi masalah saat koneksi database
        e.printStackTrace(); // Debugging (bisa dihapus di production)
        JOptionPane.showMessageDialog(this, 
            "Gagal menghubungkan ke database: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE
        );
    }
        setTitle("Sistem Parkir UNSIKA");
        setSize(800, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    private void tampilkanData() {
    try (Connection conn = DBConnection.getConnection()) {
        String sql = "SELECT * FROM parkir";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tbl_dataParkir.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("npm"),
                rs.getString("nama"),
                rs.getString("no_polisi"),
                rs.getString("no_tiket"),
                rs.getString("jenis_kendaraan"),
                rs.getTimestamp("jam_masuk"),
                rs.getTimestamp("jam_keluar"),
                rs.getInt("durasi"),
                rs.getDouble("total_biaya")
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TFNoPol = new javax.swing.JTextField();
        TFNoTiket = new javax.swing.JTextField();
        TFJamM = new javax.swing.JTextField();
        BTNMasuk = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        CMBKendaraan = new javax.swing.JComboBox<>();
        TFNPM = new javax.swing.JTextField();
        TFNama = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        TFNoTiket1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TFDurasi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TFJamM1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TFJamK1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TFBiaya = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TFNoPol1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        BTNKeluar = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        CMBKendaraan1 = new javax.swing.JComboBox<>();
        TFNPM1 = new javax.swing.JTextField();
        TFNama1 = new javax.swing.JTextField();
        CLEAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dataParkir = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblParkirKeluar = new javax.swing.JTable();
        BTNLogout = new javax.swing.JButton();
        BTNHome = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SISTEM PARKIR UNSIKA");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/unsikaFIX.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane4.setPreferredSize(new java.awt.Dimension(370, 497));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("No. Polisi :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("No. Tiket :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Jam masuk :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("NPM :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Nama :");

        TFNoPol.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFNoPol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFNoPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNoPolActionPerformed(evt);
            }
        });

        TFNoTiket.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFNoTiket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFNoTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNoTiketActionPerformed(evt);
            }
        });

        TFJamM.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFJamM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFJamM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFJamMActionPerformed(evt);
            }
        });

        BTNMasuk.setBackground(new java.awt.Color(0, 255, 0));
        BTNMasuk.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BTNMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enterr.png"))); // NOI18N
        BTNMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMasukActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel46.setText("Jenis Kendaraan :");

        CMBKendaraan.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        CMBKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));
        CMBKendaraan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TFNPM.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFNPM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TFNama.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFNama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel46)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TFNama)
                    .addComponent(TFNoPol)
                    .addComponent(TFNoTiket)
                    .addComponent(BTNMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFNPM)
                    .addComponent(CMBKendaraan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFJamM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TFNPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFNoPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNoTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMBKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFJamM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Parkir Masuk", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jScrollPane3.setPreferredSize(new java.awt.Dimension(394, 519));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        TFNoTiket1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFNoTiket1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFNoTiket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNoTiket1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Jam Masuk :");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Jam Keluar :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Biaya :");

        TFDurasi.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFDurasi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFDurasiActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("NPM :");

        TFJamM1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFJamM1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFJamM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFJamM1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Nama :");

        TFJamK1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFJamK1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFJamK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFJamK1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("No. Polisi :");

        TFBiaya.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFBiaya.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBiayaActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("No. Tiket :");

        TFNoPol1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFNoPol1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TFNoPol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNoPol1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("Durasi :");

        BTNKeluar.setBackground(new java.awt.Color(102, 0, 0));
        BTNKeluar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BTNKeluar.setForeground(new java.awt.Color(255, 255, 255));
        BTNKeluar.setText("ENTER");
        BTNKeluar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKeluarActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel47.setText("Jenis Kendaraan :");

        CMBKendaraan1.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        CMBKendaraan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mobil", "Motor" }));
        CMBKendaraan1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TFNPM1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFNPM1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TFNama1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        TFNama1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CLEAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exitt.png"))); // NOI18N
        CLEAR.setToolTipText("");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFNoTiket1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFJamK1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNKeluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFNPM1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFNoPol1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TFNama1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CMBKendaraan1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFJamM1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFDurasi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFBiaya))
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TFNoTiket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(TFJamK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFNPM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFNoPol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFJamM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(CMBKendaraan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(839, 839, 839))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Parkir Keluar", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 450, 880));

        tbl_dataParkir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        tbl_dataParkir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tbl_dataParkir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NPM", "Nama", "No. Polisi", "No. Tiket", "Jenis Kendaraan", "Jam Masuk"
            }
        ));
        jScrollPane1.setViewportView(tbl_dataParkir);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 820, 220));

        tblParkirKeluar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        tblParkirKeluar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblParkirKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NPM", "Nama", "No. Polisi", "No. Tiket", "Jenis Kendaraan", "Jam Masuk", "Jam Keluar", "Durasi", "Biaya"
            }
        ));
        jScrollPane2.setViewportView(tblParkirKeluar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 820, 240));

        BTNLogout.setBackground(new java.awt.Color(102, 0, 0));
        BTNLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGOUT.png"))); // NOI18N
        BTNLogout.setBorder(null);
        BTNLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNLogoutMouseClicked(evt);
            }
        });
        BTNLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(BTNLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 10, 40, 40));

        BTNHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        BTNHome.setBorder(null);
        BTNHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNHomeMouseClicked(evt);
            }
        });
        getContentPane().add(BTNHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, 40, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATA PARKIR KELUAR ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 830, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA PARKIR MASUK ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 830, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Desain tanpa judul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1060));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BTNMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMasukActionPerformed
        String npm = TFNPM.getText();
        String nama = TFNama.getText();
        String noPolisi = TFNoPol.getText();
        String noTiket = TFNoTiket.getText();
        String jenisKendaraan = CMBKendaraan.getSelectedItem().toString();
        String jamMasuk = TFJamM.getText();
        try {
            ParkingDAO.simpanData(npm, nama, noPolisi, noTiket, jenisKendaraan, jamMasuk);
        } catch (Exception e) {
            e.printStackTrace(); 
        }
        tampilkanData();
    }//GEN-LAST:event_BTNMasukActionPerformed

    private void TFJamMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFJamMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFJamMActionPerformed

    private void TFNoTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNoTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNoTiketActionPerformed

    private void TFNoPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNoPolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNoPolActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     LoadData.loadDataToTable(tbl_dataParkir);
     LoadData.loadDataToTable(tblParkirKeluar);
    }//GEN-LAST:event_formWindowOpened

    private void BTNKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKeluarActionPerformed
        try {
            String noTiket = TFNoTiket1.getText();
            String jamKeluar = TFJamK1.getText(); // Format: "yyyy-MM-dd HH:mm:ss"

            ParkingDAO dao = new ParkingDAO();

            // Ambil data berdasarkan nomor tiket
            ParkingData data = dao.getParkingDataByTicket(noTiket);
            if (data == null) {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan untuk No Tiket: " + noTiket);
                return;
            }

            // Isi field otomatis
            TFNPM1.setText(data.getNpm());
            TFNama1.setText(data.getNama());
            TFNoPol1.setText(data.getNoPolisi());
            CMBKendaraan1.setSelectedItem(data.getJenisKendaraan());
            TFJamM1.setText(data.getJamMasuk());

            // Hitung durasi dan biaya
            CalculationResult result = dao.calculateParking(data.getJamMasuk(), jamKeluar, data.getJenisKendaraan());
            TFDurasi.setText(result.getDurationHours() + " Jam");
            TFBiaya.setText("Rp" + result.getTotalCost());

            // Update database
            dao.updateParkingData(noTiket, jamKeluar, result.getDurationHours(), result.getTotalCost());

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_BTNKeluarActionPerformed

    private void TFNoPol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNoPol1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNoPol1ActionPerformed

    private void TFBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFBiayaActionPerformed

    private void TFJamK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFJamK1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFJamK1ActionPerformed

    private void TFJamM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFJamM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFJamM1ActionPerformed

    private void TFDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFDurasiActionPerformed

    private void TFNoTiket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNoTiket1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNoTiket1ActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
    try {
        String npm = TFNPM.getText();
        String nama = TFNama.getText();
        String noPolisi = TFNoPol.getText();
        String noTiket = TFNoTiket.getText();
        String jenisKendaraan = CMBKendaraan.getSelectedItem().toString();
        String jamMasuk = TFJamM.getText();
        String jamKeluar = TFJamK1.getText();
        String durasi = TFDurasi.getText();
        String biaya = TFBiaya.getText();

        // Simpan ke dalam JTable (atau database jika dibutuhkan)
        DefaultTableModel model = (DefaultTableModel) tblParkirKeluar.getModel();
        model.addRow(new Object[]{npm, nama, noPolisi,noTiket, jamMasuk, jamKeluar, jenisKendaraan, durasi, biaya});

        JOptionPane.showMessageDialog(this, "Palang pintu telah dibuka!");
        
        TFNPM.setText("");
        TFNama.setText("");
        TFNoPol.setText("");
        TFNoTiket.setText("");
        CMBKendaraan.setSelectedIndex(0);
        TFJamM.setText("");
        TFJamK1.setText("");
        TFDurasi.setText("");
        TFBiaya.setText("");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_CLEARActionPerformed

    private void BTNLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLogoutActionPerformed
     // Tampilkan dialog konfirmasi logout
    int response = JOptionPane.showConfirmDialog(
            this, // Parent component
            "Apakah Anda yakin ingin logout?", // Pesan
            "Konfirmasi Logout", // Judul dialog
            JOptionPane.YES_NO_OPTION, // Tipe tombol
            JOptionPane.QUESTION_MESSAGE // Ikon
    );

    // Jika pengguna memilih "Yes"
    if (response == JOptionPane.YES_OPTION) {
        // Tampilkan halaman login
        new LOGINPAGE().setVisible(true);

        // Tutup halaman saat ini
        dispose();
    }
    }//GEN-LAST:event_BTNLogoutActionPerformed

    private void BTNLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNLogoutMouseClicked

    }//GEN-LAST:event_BTNLogoutMouseClicked

    private void BTNHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNHomeMouseClicked
    new HOME().setVisible(true);
    dispose();
    }//GEN-LAST:event_BTNHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PARKIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PARKIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PARKIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PARKIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PARKIR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNHome;
    private javax.swing.JButton BTNKeluar;
    private javax.swing.JButton BTNLogout;
    private javax.swing.JButton BTNMasuk;
    private javax.swing.JButton CLEAR;
    private javax.swing.JComboBox<String> CMBKendaraan;
    private javax.swing.JComboBox<String> CMBKendaraan1;
    private javax.swing.JTextField TFBiaya;
    private javax.swing.JTextField TFDurasi;
    private javax.swing.JTextField TFJamK1;
    private javax.swing.JTextField TFJamM;
    private javax.swing.JTextField TFJamM1;
    private javax.swing.JTextField TFNPM;
    private javax.swing.JTextField TFNPM1;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFNama1;
    private javax.swing.JTextField TFNoPol;
    private javax.swing.JTextField TFNoPol1;
    private javax.swing.JTextField TFNoTiket;
    private javax.swing.JTextField TFNoTiket1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblParkirKeluar;
    private javax.swing.JTable tbl_dataParkir;
    // End of variables declaration//GEN-END:variables
}
